// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skztomqxkxjtxeuzrgrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrenRvbXF4a3hqdHhldXpyZ3JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDcyODcsImV4cCI6MjA2MzkyMzI4N30.XKbqjdLx1dn8Hu_0_W3eSfLq3_8tJC89TaDfP6cbTng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);